# Generated by Django 4.0.5 on 2022-06-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingagenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
