# Generated by Django 4.0.5 on 2022-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_alter_meeting_meetingagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourcedescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
